//Error Handling
try{
    console.log(a)
}
catch(error){
    console.log("Something went wrong")
    }